version: "3.9"
services:
  files:
    container_name: files
    ports:
    - 8080:80
    build:
      context: .
      dockerfile: Serve.Dockerfile
  app:
    build:
      context: .
    environment:
      - FILE_SERVER=http://files
    links:
      - files
    depends_on:
      - "files"